# Generated by Django 4.1.7 on 2023-03-10 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Track_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=150)),
                ('length', models.CharField(max_length=100)),
                ('turns', models.CharField(max_length=2)),
                ('seating_capacity', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('tracktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Types', to='racedayapi.track_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Series_Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Series_Relationships', to='racedayapi.series')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Track_Relationships', to='racedayapi.track')),
            ],
        ),
    ]
